### ISSUE TITLE
 'opencv2/calib3d/calib3d_c.h' file not found

### ISSUE THREAD

**Issue by viniciolindo** [roymacdonald/ofxGLWarper#10]
with OF 0.9.3 this file is not present inside opencv addons

**Comment by roymacdonald** [comment]
Hi, it's working for me. I just tried it with a fresh OF download on OSX.
Which OS/IDE are you using?
The only thing I had to do was to remove ofxOpencv from the xcode project and update the project using project generator.

**Comment by viniciolindo** [comment]
hi, i'm using of 0.9.3 on mac os 10.11.6 with Xcode 7.3.1.
ok i will try to update xcode project but I don't understand why you include this file that is not present in the fresh installation of openframeworks

**Comment by roymacdonald** [comment]
Hi I just updated the xcode projects to OF 0.9.3. Just redownload or pull.
the xcode projects were somehow old. The missing file used to be there but in the newer version it was not.
cheers

**Comment by viniciolindo** [comment]
it doesn't work. Sorry if i persist but that file doesn't exist in of 0.9.3 so cannot explain how you can include it in your ofxGLWarper.cpp

**Comment by roymacdonald** [comment]
Hey @viniciolindo I figured out what was going on.
I was using openframeworks' github head which has the  calib3d_c.h file, which, for some reason, is not included in the osx release.
I fixed it, and tried on osx 10.11.6, xcode 7.3 and of_v0.9.3_osx_release.
just redownload or pull. 
let me know if it works now.
cheers

**Comment by viniciolindo** [comment]
oh very good thank's
cheers
