### ISSUE TITLE
Bug when multiple warping

### ISSUE THREAD

**Issue by CyrCom** [roymacdonald/ofxGLWarper#14]
Hey, I had this issue on Raspberry and same when I try on windows.
There is a specific angle where source disappears, but it depends on the warper number ........
e.g. the number one doesn't disappear.
Try with the example-MultiWarpers, it's hard to define but see on this GIF
Where to look ? I hope you're still warm for this kind of math gymnastic ^^ Me... I prefer to ask first ;)
![ofxglwarper bug](https://user-images.githubusercontent.com/8659935/42289939-bf6b297a-7fc2-11e8-9a07-cc845fec0a0f.gif)

**Comment by roymacdonald** [comment]
Hi, I'm not really sure. I haven't used this addon for a while. I will take a look later. I have some ideas of what it can be.

**Comment by CyrCom** [comment]
Ok.
Feel free to give me some of your ideas that I could try to investigate.


Le mer. 4 juil. 2018 21:04, Roy Macdonald <notifications@github.com> a
écrit :

**Comment by roymacdonald** [comment]
if you move the top left quads corners somewhere else, does it behave in the same way? I mean, its corners have cordinates that are zero, so that might be making it behave in a different way

**Comment by CyrCom** [comment]
Yes it tried to move the whole somewhere else, and it is still behaving
correctly for this number 1.

Le mer. 4 juil. 2018 21:08, Roy Macdonald <notifications@github.com> a
écrit :

**Comment by roymacdonald** [comment]
mmm, I'll have to check later.

**Comment by CyrCom** [comment]
You're right, it is related to setup coordinates. when called 
`ofxGLWarper::setup(int _x, int _y, int _w, int _h)`
and _x and _y are not == 0:
![ofxglwarper bug2](https://user-images.githubusercontent.com/8659935/42292234-56d9abfc-7fd1-11e8-8618-1a63ca524b41.gif)

**Comment by roymacdonald** [comment]
I was checking and the problem seems to be something part of OpenCV. 
check it here https://github.com/roymacdonald/ofxGLWarper/tree/fix-multiwrappers

It can be fixed and modifying the api slightly.

**Comment by CyrCom** [comment]
Hey,
I commented your commit, I changed from OpenCV to an ArturoC method via a
embedded file. All examples are working exactly the same.... with the same
problem.
Are you interested in this method if I propose a Pull Request ? I saw
comments saying "we should get rid of OpenCV". This is indeed less includes
and much cleaner code.

2018-07-05 22:34 GMT+02:00 Roy Macdonald <notifications@github.com>:
