### ISSUE TITLE
build errors in the examples

### ISSUE THREAD

**Issue by nylki** [roymacdonald/ofxGLWarper#6]
Hi there,
2012 since the last commit is quite a while so some problems might be expected.
I got some errors, trying to build the *a_bit_more_complex_example* but similiar errors were found in the simple example.
I am on OS X, 10.9 and XCode 5.1.1.

>
Undefined symbols for architecture i386:
  "_CVDisplayLinkGetNominalOutputVideoRefreshPeriod", referenced from:
      _vidmodeFromCGDisplayMode in libglfw3.a(cocoa_monitor.m.o)
  "_CVDisplayLinkCreateWithCGDisplay", referenced from:
      __glfwSetVideoMode in libglfw3.a(cocoa_monitor.m.o)
      __glfwPlatformGetVideoMode in libglfw3.a(cocoa_monitor.m.o)
      __glfwPlatformGetVideoModes in libglfw3.a(cocoa_monitor.m.o)
  "_CVDisplayLinkRelease", referenced from:
      __glfwSetVideoMode in libglfw3.a(cocoa_monitor.m.o)
      __glfwPlatformGetVideoMode in libglfw3.a(cocoa_monitor.m.o)
      __glfwPlatformGetVideoModes in libglfw3.a(cocoa_monitor.m.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

Have you got a pointer on how to fix this issue? Or if this addon is deprecated, is there a replacement?

**Comment by nylki** [comment]
Apparently the issue is the missing CoreVideo framework. See thread:
http://forum.openframeworks.cc/t/fix-for--cvdisplaylinkrelease-etc-errors/16423

After adding CoreVideo I was able to build the examples.

**Comment by roymacdonald** [comment]
Hi,
right, since OF 0.8 some frameworks need to be added to be able to build. I'll update the example projects to the current release.
best
