### ISSUE TITLE
update for new oF versions

### ISSUE THREAD

**Issue by martialgallorini** [roymacdonald/ofxGLWarper#7]
hello,

thanks for this addon !

any chance you update it to make it compatible with oF09 ?

Can't build it as is under OSX El Capitan with oF09

thanks a lot

**Comment by roymacdonald** [comment]
Hi,
done! :)
Thanks for reminding me of it.
Best!

**Comment by martialgallorini** [comment]
well ! efficient ;)

thanks a lot !
